// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bufiyccsjewfgacneimc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1Zml5Y2NzamV3ZmdhY25laW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTk3MzIsImV4cCI6MjA2NTU5NTczMn0.85trQUkSVpLijQc9EPW4BF8Vy9jAZ8jR5zI6E4ssgLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);